<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Page;

$p = Page::where('slug', 'sitemap')->first();
if($p) {
    $p->update(['content' => '<h2>Sitemap</h2><p>Navigate through all the sections of our website using the links below.</p><h3><i class="fa-solid fa-house text-primary mr-2"></i> Main Pages</h3><ul class="list-disc ml-4 space-y-2 mt-3"><li><a href="/" class="text-primary hover:underline hover:text-green-700">Home</a> &mdash; Welcome page with latest updates and department overview</li><li><a href="/about" class="text-primary hover:underline hover:text-green-700">About Us</a> &mdash; Department history, vision, mission, and facilities</li><li><a href="/academics" class="text-primary hover:underline hover:text-green-700">Academics</a> &mdash; Programme categories, courses, and academic structure</li><li><a href="/people" class="text-primary hover:underline hover:text-green-700">Faculty & Staff</a> &mdash; Meet our lecturers, administrative, and technical staff</li><li><a href="/news-events" class="text-primary hover:underline hover:text-green-700">News & Events</a> &mdash; Stay updated on department happenings</li></ul><h3><i class="fa-solid fa-info-circle text-primary mr-2"></i> About Information</h3><ul class="list-disc ml-4 space-y-2 mt-3"><li><a href="/about#our-story" class="text-primary hover:underline hover:text-green-700">Our Story</a></li><li><a href="/about#vision-mission" class="text-primary hover:underline hover:text-green-700">Vision & Mission</a></li><li><a href="/about#core-values" class="text-primary hover:underline hover:text-green-700">Core Values</a></li><li><a href="/about#facilities" class="text-primary hover:underline hover:text-green-700">Facilities & Labs</a></li><li><a href="/about#our-faculty" class="text-primary hover:underline hover:text-green-700">Our Faculty List</a></li></ul><h3><i class="fa-solid fa-file-alt text-primary mr-2"></i> Legal & Documentation</h3><ul class="list-disc ml-4 space-y-2 mt-3"><li><a href="/page/privacy-policy" class="text-primary hover:underline hover:text-green-700">Privacy Policy</a></li><li><a href="/page/terms-of-use" class="text-primary hover:underline hover:text-green-700">Terms of Use</a></li><li><a href="/page/sitemap" class="text-primary hover:underline hover:text-green-700">Sitemap</a> (this page)</li></ul>']);
}

$p = Page::where('slug', 'terms-of-use')->first();
if($p) {
    $p->update(['content' => '<h2>Terms of Use</h2><p><strong>Last Updated:</strong> January 1, 2026</p><p>By accessing and using the Department of Computer Science, NSUK website, you agree to be bound by the following terms.</p><h3>1. Acceptance of Terms</h3><p>By using this website, you acknowledge that you have read, understood, and agree to these Terms of Use. If you do not agree, please discontinue use immediately.</p><h3>2. Intellectual Property</h3><p>All content on this website, including text, graphics, logos, and software, is the property of the Department of Computer Science, NSUK. Unauthorized reproduction is strictly prohibited.</p><h3>3. User Conduct</h3><p>You agree not to use the website for any unlawful purpose or in any way that could damage, disable, overburden, or impair the site connectivity.</p><h3>4. Educational Material</h3><p>Materials provided on this site are for educational and informational purposes only. Official university prospectuses and handbooks take precedence if conflict occurs.</p><h3>5. Third-Party Sites</h3><p>Our website may contain links to external sites. We are not responsible for the content or privacy practices of these sites.</p><h3>6. Limitation of Liability</h3><p>The Department shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of this website.</p>']);
}

$p = Page::where('slug', 'privacy-policy')->first();
if($p) {
    $p->update(['content' => '<h2>Privacy Policy</h2><p><strong>Effective Date:</strong> January 1, 2026</p><p>The Department of Computer Science, Nasarawa State University Keffi ("we", "us", or "our") is committed to protecting the privacy of all visitors, students, staff, and stakeholders who access our website and online services.</p><h3>1. Information We Collect</h3><p>We may automatically collect the following types of information when you interact with our website:</p><ul class="list-disc ml-4 space-y-2 mt-3"><li><strong>Personal Information:</strong> Name, matriculation number, email, and phone number when explicitly submitted through forms.</li><li><strong>Usage Data:</strong> Pages visited, browser type, IP address, and time spent on the site via anonymized analytics.</li></ul><h3>2. How We Use Your Information</h3><p>We use information responsibly to:</p><ul class="list-disc ml-4 space-y-2 mt-3"><li>Respond to your inquiries and support requests efficiently.</li><li>Improve the functionality and UX of our departmental website.</li><li>Send important academic updates and event announcements.</li></ul><h3>3. Data Protection</h3><p>We implement standard security measures to protect your data from unauthorized access or disclosure. We do not sell or rent your personal information to third parties under any circumstance.</p><h3>4. Cookies</h3><p>Our website may use cookies to enhance user experience. You can disable cookies in your browser settings, though some site features may not function optimally as a result.</p><h3>5. Updates to This Policy</h3><p>We may update this privacy policy periodically. Changes will be posted on this page with an updated effective date. For data enquiries, contact <a href="mailto:info@dcms.nsuk.edu.ng" class="text-primary hover:underline">info@dcms.nsuk.edu.ng</a>.</p>']);
}

echo "Successfully updated database pages\n";
